name: Tự động Deploy lên Docker Hub

on:
  push:
    branches: [ "main" ]   # chạy khi push code
    tags:
      - 'v*'               # chạy khi push tag v1.0, v2.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Bước 1: Checkout code
      - name: Bước 1 - Checkout code từ Github
        uses: actions/checkout@v6.0.2

      # 🔹 Bước 2: Đăng nhập Docker Hub
      - name: Bước 2 - Login Docker Hub
        uses: docker/login-action@v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔹 Bước 3: Lấy version
      - name: Bước 3 - Lấy version
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=v1.0
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # 🔹 Bước 4: Build & Push Backend
      - name: Bước 4 - Build & Push Backend
        uses: docker/build-push-action@v7.0.0
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-app:${{ steps.vars.outputs.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # 🔹 Bước 5: Build & Push Frontend
      - name: Bước 5 - Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./cv-profile
          file: ./cv-profile/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-frontend:${{ steps.vars.outputs.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
